Logging System/Controllers/MentorController.cs
using Logging_System.EFramework;
using Logging_System.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.Data;
using Learn.BL;
using System.Net.Mail;
using System.IO;
using System.IO.Compression;


namespace Logging_System.Controllers
{

    public class MentorController : Controller
    {
        // GET: Mentor

        public ActionResult Login()
        {
            return View();
        }


        [Authorize]
        public ActionResult Register()
        {

           return View();
        }

        [HttpPost]
        public ActionResult ProcessForm(List<string> selectedfiles)
        {
            if (System.IO.File.Exists(Server.MapPath
                              ("~/ZippedWeeklyLogbooks/WeeklyLogbooks.zip")))
            {
                System.IO.File.Delete(Server.MapPath
                              ("~/ZippedWeeklyLogbooks/WeeklyLogbooks.zip"));
            }
            ZipArchive zip = ZipFile.Open(Server.MapPath
                     ("~/ZippedWeeklyLogbooks/WeeklyLogbooks.zip"), ZipArchiveMode.Create);
            foreach (string file in selectedfiles)
            {
                zip.CreateEntryFromFile(Server.MapPath
                     ("~/WeeklyLogbooks/" + file), file);
            }
            zip.Dispose();
            return File(Server.MapPath("~/ZippedWeeklyLogbooks/WeeklyLogbooks.zip"),
                      "application/zip", "WeeklyLogbooks.zip");
        }
        [HttpPost]
        public ActionResult ProcessEvaluation(List<string> selectedfiles)
        {
            if (System.IO.File.Exists(Server.MapPath("~/ZippedMonthlyEvaluationForms/MonthlyEvaluationForms.zip")))

            {
                System.IO.File.Delete(Server.MapPath("~/ZippedMonthlyEvaluationForms/MonthlyEvaluationForms.zip"));

            }
            ZipArchive zip = ZipFile.Open(Server.MapPath("~/ZippedMonthlyEvaluationForms/MonthlyEvaluationForms.zip"), ZipArchiveMode.Create);

            foreach (string file in selectedfiles)
            {
                zip.CreateEntryFromFile(Server.MapPath("~/Monthly Evaluation Forms/" + file), file);

            }
            zip.Dispose();
            return File(Server.MapPath("~/ZippedMonthlyEvaluationForms/MonthlyEvaluationForms.zip"),
                      "application/zip", "MonthlyEvaluationForms.zip");
        }
        //public FileResult Downloads(string ImageName)
        //{
        //    var FileVirtualPath = "~/WeeklyLogbooks/" + ImageName;
        //    return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
        //}
        [Authorize]
        public ActionResult Download()
        {

            //var dir = new System.IO.DirectoryInfo(Server.MapPath("~/WeeklyLogbooks/"));
            //System.IO.FileInfo[] fileNames = dir.GetFiles("*.*"); List<string> items = new List<string>();
            //foreach (var file in fileNames)
            //{
            //    items.Add(file.Name);
            //}
            //return View(items);


            string[] files = Directory.GetFiles(
                 Server.MapPath("~/WeeklyLogbooks"));
            List<string> downloads = new List<string>();
            foreach (string file in files)
            {
                downloads.Add(Path.GetFileName(file));
            }
            return View(downloads);
        }


       
        //public FileResult Downloadings(string Monthly)
        //{
        //    var FileVirtualPath = "~/Monthly Evaluation Forms/" + Monthly;
        //    return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
        //}



        [Authorize]
        public ActionResult DownloadMEF()
        {


            //var dir = new System.IO.DirectoryInfo(Server.MapPath("~//Monthly Evaluation Forms/"));
            ////System.IO.FileInfo[] fileNames = dir.GetFiles("*.*"); List<string> items = new List<string>();
            //System.IO.FileInfo[] fileNames = dir.GetFiles("*"); List<string> items = new List<string>();
            //foreach (var file in fileNames)
            //{
            //    items.Add(file.Name);
            //}
            //return View(items);




            //string evaluationpath = "~/Monthly Evaluation Forms";

            //string[] files = Directory.GetFiles(Server.MapPath(evaluationpath));

            //List<string> downloads = new List<string>();
            //foreach (string file in files)
            //{
            //    downloads.Add(Path.GetFileName(file));
            //}
            //return View(downloads);

           

            string path = Server.MapPath(@"~/Monthly Evaluation Forms");
            List<string> picFolders = new List<string>();

            DirectoryInfo dirInfo = new DirectoryInfo(path);

            if (dirInfo.GetFiles("*.*").Length > 0)
                picFolders.Add(dirInfo.Name);

            foreach (var dir in dirInfo.GetDirectories())
            {
                if (dir.GetFiles("*", SearchOption.AllDirectories).Length > 0)
                    picFolders.Add(dir.Name);
            }

            return View(picFolders);
          





        }


        [Authorize]
        [HttpPost]
        public ActionResult Register(Learners _learners)
        {
            if (ModelState.IsValid)
            {
                Learners _lear = new Learners();
                string result = _lear.InsertRegDetails(_learners);
                ViewData["result"] = result;
                ModelState.Clear();
                return View();
            }
            else
            {
                ModelState.AddModelError(string .Empty,"Could Not Register Learner");
                return View();
            }
           
        }


      
        public ActionResult DoLogin(string txtUsername, string txtPassword)
        {
            Dal dal = new Dal();
            MentorLogin mentorlogin = new MentorLogin();
            ViewBag.Error = "Username or Password is incorret";

            try
            {
              mentorlogin = (
              from frm in dal.mentors.ToList()
              where frm.Username == txtUsername && frm.Password == txtPassword && frm.IsActive == true
              select frm).Single();
            }
            catch (Exception)
            {

                ViewBag.Error = "Username or Password is incorrect.";
                return View("Login");
            }

          

            if (mentorlogin != null)
            {
                Session["FirstName"] = mentorlogin.FirstName.ToString();
                Session["Surname"] = mentorlogin.Surname.ToString();
                //Session["Role"] = mentorlogin.Role.ToString();

                FormsAuthentication.SetAuthCookie(mentorlogin.Username, false);
                return RedirectToAction("Sign", "Sign");

            }
            else
            {
                return View("Login");
            }

        }
        [Authorize]
        public ActionResult Logout()
        {

            FormsAuthentication.SignOut();
            
            return View("Login");
        }

      
    }
}

Logging System/Controllers/SignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Logging_System.Controllers
{
    public class SignController : Controller
    {
        // GET: Sign
        [Authorize]
        public ActionResult Sign()
        {
            return View();
        }

        public ActionResult Logout()
        {

            FormsAuthentication.SignOut();
            return RedirectToAction("Login", "Mentor");
        }
    }
}

Logging System/Controllers/WeeklyController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Logging_System.Models;

namespace Logging_System.Controllers
{
    public class WeeklyController : Controller
    {
        // GET: Weeky
        [Authorize]
        public ActionResult WeeklyDownloads(string path)
        {
            string realPath;
            realPath = Server.MapPath("~/WeeklyLogbooks/" + path);
            // or realPath = "FullPath of the folder on server" 

            if (System.IO.File.Exists(realPath))
            {
                //http://stackoverflow.com/questions/1176022/unknown-file-type-mime
                return base.File(realPath, "application/octet-stream");
            }
            else if (System.IO.Directory.Exists(realPath))
            {

                Uri url = Request.Url;
                //Every path needs to end with slash
                if (url.ToString().Last() != '/')
                {
                    Response.Redirect("/Weekly/" + path + "/");
                }

                List<DirModel> dirListModel = new List<DirModel>();

                IEnumerable<string> dirList = Directory.EnumerateDirectories(realPath);
                foreach (string dir in dirList)
                {
                    DirectoryInfo d = new DirectoryInfo(dir);

                    DirModel dirModel = new DirModel();

                    dirModel.DirName = Path.GetFileName(dir);
                    dirModel.DirAccessed = d.LastAccessTime;

                    dirListModel.Add(dirModel);
                }


                List<FileModel> fileListModel = new List<FileModel>();

                IEnumerable<string> fileList = Directory.EnumerateFiles(realPath);
                foreach (string file in fileList)
                {
                    FileInfo f = new FileInfo(file);

                    FileModel fileModel = new FileModel();

                    if (f.Extension.ToLower() != "php" && f.Extension.ToLower() != "aspx"
                        && f.Extension.ToLower() != "asp")
                    {
                        fileModel.FileName = Path.GetFileName(file);
                        fileModel.FileAccessed = f.LastAccessTime;
                        fileModel.FileSizeText = (f.Length < 1024) ? f.Length.ToString() + " B" : f.Length / 1024 + " KB";

                        fileListModel.Add(fileModel);
                    }
                }

                ExplorerModel explorerModel = new ExplorerModel(dirListModel, fileListModel);

                return View(explorerModel);
            }
            else
            {
                return Content(path + " is not a valid file or directory.");
            }
        }
    }
}

Logging System/Views/Sign/Sign.cshtml
@{
    ViewBag.Title = "Login";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Mentor Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Css/Learner.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery-3.1.1.js"></script>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>

    <div class="container">

        <div class="form-horizontal">
            <br />

            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title" style="text-align:center;">Mentors Portal</h3>
                </div>
                <div class="panel-body" style="text-align:left;">


                    <div class="logged">
                        @if (Session["FirstName"] != null || Session["Surname"] != null)
            {
                            <text>
                                Mentor: @Session["FirstName"].ToString()  @Session["Surname"].ToString()
                            </text>
                        }
                    </div>

                </div>
            </div>
           
            
            <h2>Send Email:</h2>

            <div class="form-group">

                <div class="col-xs-2">
                    <label for="mesage">Email:</label>
                    <input type="email" class="form-control" name="txtEmail" id="txtEmail"  placeholder="Enter Email Address" autofocus>

                </div>
            </div>



            <div class="form-group">

                <div class="col-xs-4">
                    <label for="comment">Comment:</label>
                    <textarea class="form-control" rows="5" id="body-message"></textarea>
                </div>


            </div>


            

                <input type="submit" name="btnsubmit" class="btn btn-primary"  style="margin:3px;" value="Send" />
                <input type="button" name="submit" class="btn btn-primary"  style="margin:3px;" value="Back" onclick="location.href='@Url.Action("Login", "Mentor")'" />
                <input type="button" name="submit" class="btn btn-primary"  style="margin:3px;" value="Register New Learner" onclick="location.href='@Url.Action("Register", "Mentor")'" />
                <input type="button" name="submit" class="btn btn-primary"  style="margin:3px;" value="Logbooks" onclick="location.href='@Url.Action("WeeklyDownloads", "Weekly")'" />
            <input type="button" name="submit" class="btn btn-primary"  style="margin:3px;" value="Monthly Evaluation Forms" onclick="location.href='@Url.Action("MonthlyDownloads", "Monthly")'" />
            <input type="button" name="submit" class="btn btn-primary"  style="margin:3px;" value="Learners Database" onclick="location.href='@Url.Action("RegisteredLearners", "Registered")'" />
            <input type="button" name="submit" class="btn btn-primary"  style="margin:3px;" value="Download POA" onclick="location.href='@Url.Action("Downloads", "LearnersHome")'" />

                <input type="button" name="submit" class="btn btn-primary"  style="margin:3px;" value="Logout" onclick="location.href='@Url.Action("Logout", "Mentor")'" />



        </div>
      </div>
  

</body>
</html>