Logging System/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Logging_System.Controllers
{
    public class HomeController : Controller
    {
        
        //GET:
        public ActionResult Index() 
        {
            return View();
        }

      

    }
}

Logging System/Controllers/LearnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Logging_System.Models;
using Logging_System.EFramework;
using System.Web.Security;
using Learn.BL;

namespace Logging_System.Controllers
{
  
    public class LearnerController : Controller
    {
        //
        // GET: /Learner/
        
        public ActionResult Login()
        {
            return View();

        }

        public ActionResult DoLogin(string txtUsername, string txtPassword)
        {
        //    string message = "Username or Password is incorrect";
            Dal odal = new Dal();
            LearnersDetails learnerlogin = new LearnersDetails();
           
            try
            {
              learnerlogin = (
              from frm in odal.learners.ToList()
              where frm.Username == txtUsername && frm.Password == txtPassword && frm.IsUserActive == true
              select frm).Single();
            }
            catch (Exception)
            {
                ViewBag.Error = "Username or Password is incorrect.";
                return View("Login");
            }


            if (learnerlogin != null)
            {


                Session["Names"] = learnerlogin.Names;
                Session["Username"] = learnerlogin.Username;
                Session["Surname"] = learnerlogin.Surname;
                FormsAuthentication.SetAuthCookie(learnerlogin.Username, false);
                return RedirectToAction("Learner_Home", "LearnersHome");

            }
            else
            {

                return View("Login");
            }

        }
        [Authorize]
        public ActionResult Logout()
        {

            FormsAuthentication.SignOut();
            return View("Login");
        }


    }
}

Logging System/Controllers/MentorController.cs
using Logging_System.EFramework;
using Logging_System.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.Data;
using Learn.BL;
using System.Net.Mail;
using System.IO;
using System.IO.Compression;


namespace Logging_System.Controllers
{

    public class MentorController : Controller
    {
        // GET: Mentor

        public ActionResult Login()
        {
            return View();
        }


        [Authorize]
        public ActionResult Register()
        {

           return View();
        }

        [HttpPost]
        public ActionResult ProcessForm(List<string> selectedfiles)
        {
            if (System.IO.File.Exists(Server.MapPath
                              ("~/ZippedWeeklyLogbooks/WeeklyLogbooks.zip")))
            {
                System.IO.File.Delete(Server.MapPath
                              ("~/ZippedWeeklyLogbooks/WeeklyLogbooks.zip"));
            }
            ZipArchive zip = ZipFile.Open(Server.MapPath
                     ("~/ZippedWeeklyLogbooks/WeeklyLogbooks.zip"), ZipArchiveMode.Create);
            foreach (string file in selectedfiles)
            {
                zip.CreateEntryFromFile(Server.MapPath
                     ("~/WeeklyLogbooks/" + file), file);
            }
            zip.Dispose();
            return File(Server.MapPath("~/ZippedWeeklyLogbooks/WeeklyLogbooks.zip"),
                      "application/zip", "WeeklyLogbooks.zip");
        }
        [HttpPost]
        public ActionResult ProcessEvaluation(List<string> selectedfiles)
        {
            if (System.IO.File.Exists(Server.MapPath("~/ZippedMonthlyEvaluationForms/MonthlyEvaluationForms.zip")))

            {
                System.IO.File.Delete(Server.MapPath("~/ZippedMonthlyEvaluationForms/MonthlyEvaluationForms.zip"));

            }
            ZipArchive zip = ZipFile.Open(Server.MapPath("~/ZippedMonthlyEvaluationForms/MonthlyEvaluationForms.zip"), ZipArchiveMode.Create);

            foreach (string file in selectedfiles)
            {
                zip.CreateEntryFromFile(Server.MapPath("~/Monthly Evaluation Forms/" + file), file);

            }
            zip.Dispose();
            return File(Server.MapPath("~/ZippedMonthlyEvaluationForms/MonthlyEvaluationForms.zip"),
                      "application/zip", "MonthlyEvaluationForms.zip");
        }
        //public FileResult Downloads(string ImageName)
        //{
        //    var FileVirtualPath = "~/WeeklyLogbooks/" + ImageName;
        //    return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
        //}
        [Authorize]
        public ActionResult Download()
        {

            //var dir = new System.IO.DirectoryInfo(Server.MapPath("~/WeeklyLogbooks/"));
            //System.IO.FileInfo[] fileNames = dir.GetFiles("*.*"); List<string> items = new List<string>();
            //foreach (var file in fileNames)
            //{
            //    items.Add(file.Name);
            //}
            //return View(items);


            string[] files = Directory.GetFiles(
                 Server.MapPath("~/WeeklyLogbooks"));
            List<string> downloads = new List<string>();
            foreach (string file in files)
            {
                downloads.Add(Path.GetFileName(file));
            }
            return View(downloads);
        }


       
        //public FileResult Downloadings(string Monthly)
        //{
        //    var FileVirtualPath = "~/Monthly Evaluation Forms/" + Monthly;
        //    return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
        //}



        [Authorize]
        public ActionResult DownloadMEF()
        {


            //var dir = new System.IO.DirectoryInfo(Server.MapPath("~//Monthly Evaluation Forms/"));
            ////System.IO.FileInfo[] fileNames = dir.GetFiles("*.*"); List<string> items = new List<string>();
            //System.IO.FileInfo[] fileNames = dir.GetFiles("*"); List<string> items = new List<string>();
            //foreach (var file in fileNames)
            //{
            //    items.Add(file.Name);
            //}
            //return View(items);




            //string evaluationpath = "~/Monthly Evaluation Forms";

            //string[] files = Directory.GetFiles(Server.MapPath(evaluationpath));

            //List<string> downloads = new List<string>();
            //foreach (string file in files)
            //{
            //    downloads.Add(Path.GetFileName(file));
            //}
            //return View(downloads);

           

            string path = Server.MapPath(@"~/Monthly Evaluation Forms");
            List<string> picFolders = new List<string>();

            DirectoryInfo dirInfo = new DirectoryInfo(path);

            if (dirInfo.GetFiles("*.*").Length > 0)
                picFolders.Add(dirInfo.Name);

            foreach (var dir in dirInfo.GetDirectories())
            {
                if (dir.GetFiles("*", SearchOption.AllDirectories).Length > 0)
                    picFolders.Add(dir.Name);
            }

            return View(picFolders);
          





        }


        [Authorize]
        [HttpPost]
        public ActionResult Register(Learners _learners)
        {
            if (ModelState.IsValid)
            {
                Learners _lear = new Learners();
                string result = _lear.InsertRegDetails(_learners);
                ViewData["result"] = result;
                ModelState.Clear();
                return View();
            }
            else
            {
                ModelState.AddModelError(string .Empty,"Could Not Register Learner");
                return View();
            }
           
        }


      
        public ActionResult DoLogin(string txtUsername, string txtPassword)
        {
            Dal dal = new Dal();
            MentorLogin mentorlogin = new MentorLogin();
            ViewBag.Error = "Username or Password is incorret";

            try
            {
              mentorlogin = (
              from frm in dal.mentors.ToList()
              where frm.Username == txtUsername && frm.Password == txtPassword && frm.IsActive == true
              select frm).Single();
            }
            catch (Exception)
            {

                ViewBag.Error = "Username or Password is incorrect.";
                return View("Login");
            }

          

            if (mentorlogin != null)
            {
                Session["FirstName"] = mentorlogin.FirstName.ToString();
                Session["Surname"] = mentorlogin.Surname.ToString();
                //Session["Role"] = mentorlogin.Role.ToString();

                FormsAuthentication.SetAuthCookie(mentorlogin.Username, false);
                return RedirectToAction("Sign", "Sign");

            }
            else
            {
                return View("Login");
            }

        }
        [Authorize]
        public ActionResult Logout()
        {

            FormsAuthentication.SignOut();
            
            return View("Login");
        }

      
    }
}

Logging System/Views/Home/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Dynamic DNA Log System</title>
    <link rel="stylesheet" type="text/css" href="~/Css/Home.css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="shortcut icon" href="~/Images/favicon.ico" type="image/x-icon" />
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery-3.1.1.js"></script>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <link href="~/Css/font-awesome.css" rel="stylesheet" />
    <link href="~/Css/font-awesome.min.css" rel="stylesheet" />
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <script src="~/Javascript/hodeloader.js"></script>
    @{
        Layout = String.Empty;
    }
    
</head>
<body  onload="hideloader()">
    <div id="loading"></div>
    <header>

        <div class="logo text-center">
            <img src="~/Images/Dynamic.png" />
        </div>
    </header>

    <div class="container" style="padding-top:100px;padding-bottom:50px;">
        <div class="form-signin">


            <div class="logo"></div>

            @*<button class="btn sign_in" id="btnSignIn" type="button" style="color:#ffffff;font-size:20px; margin:5px; background-color:#ffffff;" onclick="location.href='@Url.Action("Login", "Administrator")'">
                <div class="loader"></div>
                @*<span class="glyphicon glyphicon-education" style="font-size:25px;padding-right:10px;color:#f39c12"></span>
                Administration*@
            @*</button>*@

            <button class="btn sign_in" id="btnSignIn" type="button" style="color:#ffffff;font-size:20px; margin:5px;" onclick="location.href='@Url.Action("Login", "Administrator")'">

                <span class="glyphicon glyphicon-education" style="font-size:25px;padding-right:10px;color:#f39c12"></span>
                Administration
            </button>

            <button class="btn sign_in" id="btnSignIn" type="button" style="color:#ffffff;font-size:20px; margin:5px;" onclick="location.href='@Url.Action("Login", "Learner")'">

                <span class="glyphicon glyphicon-log-in" style="font-size:25px;padding-right:10px;color:#ffffff"></span>
                Learners Login
            </button>

            <button class="btn sign_in" id="btnSignIn" type="button" style="color:#ffffff;font-size:20px; background-color:#f39c12; margin:5px;" onclick="location.href='@Url.Action("Login", "Mentor")'">
                <span class="glyphicon glyphicon-log-in" style="font-size:25px;padding-right:10px;color:#ffffff"></span>
                Mentors Login
            </button>


            <div class="navbar-text pull-right" >
                <a href="http://www.facebook.com" target="_blank"><i class="fa fa-facebook-square fa-2x"></i></a>
                <a href="http://www.twitter.com"target="_blank"><i class="fa fa-twitter-square fa-2x"></i></a>
                <a href="http://www.linkedin.com"target="_blank"><i class="fa fa-linkedin-square fa-2x"></i></a>
                <a href="http://www.instagram.com"target="_blank"><i class="fa fa-instagram fa-2x"></i></a>
            </div>



        </div>
    </div>
    
</body>
</html>