Logging System/Controllers/LearnersHomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Logging_System.Controllers
{   
    public class LearnersHomeController : Controller
    {
        // GET: LearnersHome
      
        [Authorize]
        public ActionResult Learner_Home()
        {
            return View();
        }



        private bool isValidContentType(string contentType)
        {
            return contentType.Equals("application/pdf") || contentType.Equals("application/vnd.openxmlformats-officedocument.wordprocessingml.document") || contentType.Equals("application/msword");
        }

        private bool isValidSizeLength(int contentLength)
        {
            return ((contentLength / 1024) / 1024) < 1; //1MB
        }

        [Authorize]
        [HttpPost]
        public ActionResult Process(HttpPostedFileBase photo)
        {
            try
            {
                if (!isValidContentType(photo.ContentType))
                {
                    ViewBag.Error = "Only Pdf & Docx files are accepted.";
                    return View("Learner_Home");
                }
                else if (!isValidSizeLength(photo.ContentLength))
                {
                    ViewBag.Error = "File Size Limit, Document should be less than 2MB";
                    return View("Learner_Home");
                }
                else
                {
                    if (photo.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(photo.FileName);
                        var path = Path.Combine(Server.MapPath("~/ProofOfAbsence"), fileName);
                        photo.SaveAs(path);
                        ViewBag.fileName = photo.FileName;
                    }
                }
            }
            catch (Exception)
            {


                ViewBag.Error = "Please select a PDF or Word file.";
                return View("Learner_Home");
            }
         
            ViewBag.fileName = photo.FileName;
            return View("Success");

        }
        //Downloading

        [Authorize]
        public ActionResult Downloads()
        {
            var dir = new System.IO.DirectoryInfo(Server.MapPath("~/ProofOfAbsence/"));
            System.IO.FileInfo[] fileNames = dir.GetFiles("*.*"); List<string> items = new List<string>();
            foreach (var file in fileNames)
            {
                items.Add(file.Name);
            }
            return View(items);
        }

        public FileResult Download(string ImageName)
        {
            var FileVirtualPath = "~/ProofOfAbsence/" + ImageName;
            return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
        }
        public ActionResult Logout()
        {

            FormsAuthentication.SignOut();
            return RedirectToAction("Login", "Learner");
        }


        [HttpPost]
        public ViewResult Learner_Home(Logging_System.Models.Email _objModelMail)
        {
            

            if (ModelState.IsValid)
            {

                MailMessage mail = new MailMessage();
                mail.To.Add(_objModelMail.Sendto);
                mail.From = new MailAddress(_objModelMail.SentFrom);
                mail.Subject = _objModelMail.Subject;
                string Body = _objModelMail.Message;
                mail.Body = Body;
                mail.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                //smtp.Port = 465;
                //smtp.Port = 2525;
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new System.Net.NetworkCredential
                ("learnerslogsystem@gmail.com", "Jedia.01");
                smtp.EnableSsl = true;
                smtp.Send(mail);
                ViewBag.Message = "Sent";
                return View("Learner_Home");
            }
            else
            {
                return View();
            }
        }
    }
}

Logging System/Controllers/MentorController.cs
using Logging_System.EFramework;
using Logging_System.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.Data;
using Learn.BL;
using System.Net.Mail;
using System.IO;
using System.IO.Compression;


namespace Logging_System.Controllers
{

    public class MentorController : Controller
    {
        // GET: Mentor

        public ActionResult Login()
        {
            return View();
        }


        [Authorize]
        public ActionResult Register()
        {

           return View();
        }

        [HttpPost]
        public ActionResult ProcessForm(List<string> selectedfiles)
        {
            if (System.IO.File.Exists(Server.MapPath
                              ("~/ZippedWeeklyLogbooks/WeeklyLogbooks.zip")))
            {
                System.IO.File.Delete(Server.MapPath
                              ("~/ZippedWeeklyLogbooks/WeeklyLogbooks.zip"));
            }
            ZipArchive zip = ZipFile.Open(Server.MapPath
                     ("~/ZippedWeeklyLogbooks/WeeklyLogbooks.zip"), ZipArchiveMode.Create);
            foreach (string file in selectedfiles)
            {
                zip.CreateEntryFromFile(Server.MapPath
                     ("~/WeeklyLogbooks/" + file), file);
            }
            zip.Dispose();
            return File(Server.MapPath("~/ZippedWeeklyLogbooks/WeeklyLogbooks.zip"),
                      "application/zip", "WeeklyLogbooks.zip");
        }
        [HttpPost]
        public ActionResult ProcessEvaluation(List<string> selectedfiles)
        {
            if (System.IO.File.Exists(Server.MapPath("~/ZippedMonthlyEvaluationForms/MonthlyEvaluationForms.zip")))

            {
                System.IO.File.Delete(Server.MapPath("~/ZippedMonthlyEvaluationForms/MonthlyEvaluationForms.zip"));

            }
            ZipArchive zip = ZipFile.Open(Server.MapPath("~/ZippedMonthlyEvaluationForms/MonthlyEvaluationForms.zip"), ZipArchiveMode.Create);

            foreach (string file in selectedfiles)
            {
                zip.CreateEntryFromFile(Server.MapPath("~/Monthly Evaluation Forms/" + file), file);

            }
            zip.Dispose();
            return File(Server.MapPath("~/ZippedMonthlyEvaluationForms/MonthlyEvaluationForms.zip"),
                      "application/zip", "MonthlyEvaluationForms.zip");
        }
        //public FileResult Downloads(string ImageName)
        //{
        //    var FileVirtualPath = "~/WeeklyLogbooks/" + ImageName;
        //    return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
        //}
        [Authorize]
        public ActionResult Download()
        {

            //var dir = new System.IO.DirectoryInfo(Server.MapPath("~/WeeklyLogbooks/"));
            //System.IO.FileInfo[] fileNames = dir.GetFiles("*.*"); List<string> items = new List<string>();
            //foreach (var file in fileNames)
            //{
            //    items.Add(file.Name);
            //}
            //return View(items);


            string[] files = Directory.GetFiles(
                 Server.MapPath("~/WeeklyLogbooks"));
            List<string> downloads = new List<string>();
            foreach (string file in files)
            {
                downloads.Add(Path.GetFileName(file));
            }
            return View(downloads);
        }


       
        //public FileResult Downloadings(string Monthly)
        //{
        //    var FileVirtualPath = "~/Monthly Evaluation Forms/" + Monthly;
        //    return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
        //}



        [Authorize]
        public ActionResult DownloadMEF()
        {


            //var dir = new System.IO.DirectoryInfo(Server.MapPath("~//Monthly Evaluation Forms/"));
            ////System.IO.FileInfo[] fileNames = dir.GetFiles("*.*"); List<string> items = new List<string>();
            //System.IO.FileInfo[] fileNames = dir.GetFiles("*"); List<string> items = new List<string>();
            //foreach (var file in fileNames)
            //{
            //    items.Add(file.Name);
            //}
            //return View(items);




            //string evaluationpath = "~/Monthly Evaluation Forms";

            //string[] files = Directory.GetFiles(Server.MapPath(evaluationpath));

            //List<string> downloads = new List<string>();
            //foreach (string file in files)
            //{
            //    downloads.Add(Path.GetFileName(file));
            //}
            //return View(downloads);

           

            string path = Server.MapPath(@"~/Monthly Evaluation Forms");
            List<string> picFolders = new List<string>();

            DirectoryInfo dirInfo = new DirectoryInfo(path);

            if (dirInfo.GetFiles("*.*").Length > 0)
                picFolders.Add(dirInfo.Name);

            foreach (var dir in dirInfo.GetDirectories())
            {
                if (dir.GetFiles("*", SearchOption.AllDirectories).Length > 0)
                    picFolders.Add(dir.Name);
            }

            return View(picFolders);
          





        }


        [Authorize]
        [HttpPost]
        public ActionResult Register(Learners _learners)
        {
            if (ModelState.IsValid)
            {
                Learners _lear = new Learners();
                string result = _lear.InsertRegDetails(_learners);
                ViewData["result"] = result;
                ModelState.Clear();
                return View();
            }
            else
            {
                ModelState.AddModelError(string .Empty,"Could Not Register Learner");
                return View();
            }
           
        }


      
        public ActionResult DoLogin(string txtUsername, string txtPassword)
        {
            Dal dal = new Dal();
            MentorLogin mentorlogin = new MentorLogin();
            ViewBag.Error = "Username or Password is incorret";

            try
            {
              mentorlogin = (
              from frm in dal.mentors.ToList()
              where frm.Username == txtUsername && frm.Password == txtPassword && frm.IsActive == true
              select frm).Single();
            }
            catch (Exception)
            {

                ViewBag.Error = "Username or Password is incorrect.";
                return View("Login");
            }

          

            if (mentorlogin != null)
            {
                Session["FirstName"] = mentorlogin.FirstName.ToString();
                Session["Surname"] = mentorlogin.Surname.ToString();
                //Session["Role"] = mentorlogin.Role.ToString();

                FormsAuthentication.SetAuthCookie(mentorlogin.Username, false);
                return RedirectToAction("Sign", "Sign");

            }
            else
            {
                return View("Login");
            }

        }
        [Authorize]
        public ActionResult Logout()
        {

            FormsAuthentication.SignOut();
            
            return View("Login");
        }

      
    }
}

Logging System/Views/LearnersHome/Downloads.cshtml
@{
    //ViewBag.Title = "Downloads";
    Layout = "~/Views/Shared/MasterPage.cshtml";
}


<!Doctype html>
<html>


<head>
    <title>Download</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery-3.1.1.js"></script>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>

    <link href="~/Css/General.css" rel="stylesheet" />
</head>
<body>

    <div class="Wrapper">
        @model List<string>
            <br />
        <br /><br />
        <h4>Learners Absenteeism Proof Download </h4>
        <br />

        <div class="container-downloads">
            <table  border="1"; style="border-color:#f39c12; border-style:double;">
                <tr>
                    <th style="color:#2b398b;">File Name</th>
                    <th style="color:#2b398b;">Download</th>
                </tr>
                @for (var i = 0; i <= Model.Count - 1; i++)
            {
                    <tr>
                        <td>@Model[i].ToString() </td>
                        <td>@Html.ActionLink("Download", "Download", new { ImageName = @Model[i].ToString() }) </td>
                    </tr>
                }


            </table>
            <div class="buttons">


                <input type="button" name="submit" class="btn btn-primary" value="Logout" onclick="location.href='@Url.Action("Logout", "Mentor")'" />
                <input type="button" name="submit" class="btn btn-primary" value="Back" onclick="location.href='@Url.Action("Sign", "Sign")'" />
                <input type="button" name="submit" class="btn btn-primary" value="Home" onclick="location.href='@Url.Action("Index", "Home")'" />
            </div>
           
        </div>

       
        </div>
   


</body>
</html>

Logging System/Views/LearnersHome/Learner_Home.cshtml
@model Logging_System.Models.Email



<!DOCTYPE html>

<html>
<head>
    <title>Learners Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Css/Learner.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery-3.1.1.js"></script>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Javascript/Upload.js"></script>
</head>
<body>


    <div class="container">

    <br /><br />

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title" style="text-align:center;">Learners Portal</h3>
            </div>
            <div class="panel-body" style="text-align:left;">


                <div class="logged">
                    @if (Session["Names"] != null || Session["Surname"] != null)
            {
                        <text>
                            Learner: @Session["Names"].ToString()  @Session["Surname"].ToString()
                        </text>
                    }
                </div>

            </div>
        </div>
        <h3 class="panel-title" style="text-align:left; color:#fdbb30; font-weight:bold;">Suggestion | Complain | Comments | Report</h3>
        <div class="panel-body">

            <div class="form-horizontal">

                @using (Html.BeginForm())
                {
                    @Html.ValidationSummary()

                    <div class="form-group">
                        <div class="col-sm-3">
                            @ViewBag.Message
                        </div>

                    </div>
                        <fieldset>

                            <div class="form-group ">

                                @Html.LabelFor(model => model.Sendto, new { @class = "col-sm-2" })

                                <div class="col-sm-3">
                                    @Html.TextBoxFor(model => model.Sendto, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Sendto)
                                </div>
                            </div>



                            <div class="form-group">
                                @Html.LabelFor(model => model.SentFrom, new { @class = "col-sm-2" })
                                <div class="col-sm-3">
                                    @Html.TextBoxFor(model => model.SentFrom, new { @class = "form-control", @Value = "learnerslogsystem@gmail.com" })
                                    @Html.ValidationMessageFor(model => model.SentFrom)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Subject, new { @class = "col-sm-2" })
                                <div class="col-sm-3">
                                    @Html.TextBoxFor(model => model.Subject, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Subject)
                                </div>
                            </div>



                            <div class="form-group">
                                @Html.LabelFor(model => model.Message, new { @class = "col-sm-2" })
                                <div class="col-sm-3">
                                    @Html.TextAreaFor(model => model.Message, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Message)
                                    <input type="submit" name="submit" class="btn btn-primary" value="Send" style="margin: 3px;" />
                                </div>

                                @*<input type="submit" name="submit" class="btn btn-primary" value="Send" />*@
                            </div>

                        </fieldset>
                }
            </div>
        </div>

        @using (Html.BeginForm("Process", "LearnersHome", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
            <div style="color:rgba(255, 0, 0, 0.88);">

                @ViewBag.Error
            </div>


                <div class="form-group">
                    <text>Only PDF and Docx are accepted</text><br />
                    <text>Only files that are 1MB or less are accepted</text>
                    <h2>Upload Proof Of Absence</h2>
                    <input type="file" id="file" class="btn btn-primary" name="photo" value="Browse File" />
                   

                    <input type="submit" class="btn btn-primary" name="Upload" value="Upload" style="margin:3px" />


                </div>
        }

        <div class="form-group">


            <input type="button" name="submit" class="btn btn-primary" value="Logbook" onclick="location.href='@Url.Action("SignLogBook", "Logbook")'" />
            <input type="button" name="submit" class="btn btn-primary" value="Evaluation Form" onclick="location.href='@Url.Action("CompleteMonthlyEvaluationForm", "MonthlyEvaluationForm")'" />
            <input type="button" name="submit" class="btn btn-primary" value="Change Password" onclick="location.href='@Url.Action("ChangePassword", "ChangePassword")'" />
            <input type="button" name="submit" class="btn btn-primary"  style="margin:3px;" value="Logout" onclick="location.href='@Url.Action("Logout", "Learner")'" />
            <input type="button" name="submit" class="btn btn-primary" value="Home"  style="margin:3px;" onclick="location.href='@Url.Action("Index", "Home")'" />

        </div>
      

    </div>



</body>
</html>

Logging System/Views/LearnersHome/Success.cshtml
@{
    //ViewBag.Title = "Success";
    Layout = "~/Views/Shared/MasterPage.cshtml";
}
<br />
<br />

<!DOCTYPE html>

<html>
<head>
    <title>Learners Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Css/Learner.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery-3.1.1.js"></script>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Javascript/Upload.js"></script>


</head>
<body>
    <div class="Wrath">

        @*<div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title" style="text-align:center;">Learners proof of absence uploads</h3>
            </div>
            <div class="panel-body" style="text-align:left;">*@


                <div class="content text-center" style="color:#2b398b;">

                    @if (Session["Names"] != null || Session["Surname"] != null)
                    {
                        <text>
                            Learner: @Session["Names"].ToString()  @Session["Surname"].ToString()
                        </text>
                    }


                    <h2>Successfully Uploaded File</h2>
                    <div class="alert" style="color:#0c7019">

                        <h3>File Uploaded Title : @ViewBag.filename</h3>

                    </div>
                </div>
            </div>
        @*</div>*@



        <div class="form-horizontal" style="text-align:center;">

            <input type="button" name="btnHome" class="btn btn-primary" value="Back" onclick="location.href='@Url.Action("Learner_Home", "LearnersHome")'" />
            <input type="button" name="btnHome" class="btn btn-primary" value="Home" onclick="location.href='@Url.Action("Index", "Home")'" />
            <input type="button" name="submit" class="btn btn-primary" value="Logout" onclick="location.href='@Url.Action("Logout", "Learner")'" /><br /><br />


            <h1>Thank You!</h1>

            <img src="~/Images/Dynamic.png" />
        </div>

   


</body>
</html>